DROP TABLE EmployeeTraining;
DROP TABLE EmployeeShift;
DROP TABLE LeaveRequest;
DROP TABLE Training;
DROP TABLE Manager;
DROP TABLE Employee2;
DROP TABLE Position;
DROP TABLE Department;
DROP TABLE Shift;
